import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
// Load the sidebars that Typedoc generates for the various modules.
// We'll build a custom hierarchy for the client and then include the
// server and shared-package APIs as their own categories.
const clientItems: any[] = require('./docs/client/typedoc-sidebar.cjs');
const serverItems: any[] = require('./docs/server-api/typedoc-sidebar.cjs');
let sharedItems: any[] = [];
try {
  sharedItems = require('./docs/shared-package/typedoc-sidebar.cjs');
} catch {
  // shared package might not have generated docs yet
  sharedItems = [];
}

// ---- client transformation --------------------------------------------------
// helper to pick items by id prefix (not used currently but left in case)
function pickByPrefix(items: any[], prefix: string) {
  const found: any[] = [];
  items.forEach(cat => {
    cat.items.forEach((item: any) => {
      if (item.id.startsWith(prefix)) {
        found.push(item);
      }
    });
  });
  return found;
}

const coreComponents = clientItems
  .find(c => c.label === 'Variables')
  ?.items.filter((i: any) =>
    /Button|DropdownMenu|Input/.test(i.id.replace('client/variables/', ''))
  ) || [];

const utilities = [
  ...(clientItems.find(c => c.label === 'Functions')?.items.filter((i: any) => i.id.includes('/cn')) || []),
  ...(clientItems.find(c => c.label === 'Variables')?.items.filter((i: any) => i.id.endsWith('buttonVariants')) || []),
];

const formTypes = clientItems
  .find(c => c.label === 'Interfaces')
  ?.items.filter((i: any) => i.id.endsWith('/Form')) || [];
const integrationTypes = clientItems
  .find(c => c.label === 'Interfaces')
  ?.items.filter((i: any) => i.id.endsWith('/Integration')) || [];

const clientCategory = {
  type: 'category',
  label: 'Client API',
  items: [
    {
      type: 'category',
      label: 'Core',
      items: [
        {type: 'category', label: 'Components', items: coreComponents},
        {type: 'category', label: 'Utilities', items: utilities},
      ],
    },
    {
      type: 'category',
      label: 'Features',
      items: [
        {type: 'category', label: 'Form Builder', items: formTypes},
        {type: 'category', label: 'Integrations', items: integrationTypes},
      ],
    },
  ],
};

// simple wrappers for the other two APIs
// serverItems come wrapped inside a "Namespaces" category; lift the inner
// array up so the sidebar shows app/core/features directly.
const serverFlattened: any[] = [];
if (serverItems.length && serverItems[0].label === 'Namespaces') {
  serverFlattened.push(...(serverItems[0].items || []));
} else {
  serverFlattened.push(...serverItems);
}
const serverCategory = {type: 'category', label: 'Server API', items: serverFlattened};

// sharedItems uses Interfaces/Functions; rename "Interfaces" to "Types"
const sharedTransformed: any[] = sharedItems.map(cat => {
  if (cat.label === 'Interfaces') {
    return {...cat, label: 'Types'};
  }
  return cat;
});
const sharedCategory = {type: 'category', label: 'Shared Package', items: sharedTransformed};

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {type: 'autogenerated', dirName: '.'},
  ],
};

export default sidebars;
